### ISSUE TITLE
Textfield needs new props

### ISSUE THREAD

**Issue by Bonn2018** [PeculiarVentures/peculiar-ui#45]
In each case where tests some "inputs" I must set testId inside Textfield => inputProps property.
Will be better to use some specific property on top-level for this.

**Comment by donskov** [comment]
While it's understandable that you're looking to streamline your testing process, it might not make sense to introduce an extra attribute like `data-testid` solely for testing purposes within React components. A better approach would be to leverage native accessibility queries like `getByRole` or `getByPlaceholderText` provided by testing libraries like Testing Library. These methods offer direct access to elements based on their inherent roles or attributes, which aligns better with best practices for testing React components (based on https://testing-library.com/docs/queries/about/#priority).

Additionally, `getByRole` tends to offer better performance compared to other querying methods. By utilizing these native querying methods, you maintain cleaner and more efficient tests without introducing unnecessary attributes solely for testing purposes (based on https://testing-library.com/docs/queries/byrole/#performance).
