### ISSUE TITLE
Tertiary button paddings inconsistent with figma layout.

### ISSUE THREAD

**Issue by alexgbv** [PeculiarVentures/peculiar-ui#6]
For Tertiatry button we should use 1px paddings. 

![image](https://user-images.githubusercontent.com/39085824/112007069-ff1f5f00-8b2c-11eb-9d8f-6dd3a0ad339f.png)
![image](https://user-images.githubusercontent.com/39085824/112007475-57eef780-8b2d-11eb-8fd2-82c1e6a4c504.png)

It is needed for adequate alignment in layouts. For example: 

![image](https://user-images.githubusercontent.com/39085824/112008233-f713ef00-8b2d-11eb-8876-0648c584ae8c.png)

**Comment by donskov** [comment]
<img width="383" alt="image" src="https://github.com/user-attachments/assets/eec33d92-7aab-49f3-b1d5-2aabe0f034b6">

Usage:
```tsx
<Button withoutPadding>
  Cancel
</Button>
```
